# Generated by Django 4.0.3 on 2022-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ashiqsabaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('klas', models.CharField(max_length=300)),
                ('info', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='upload')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
