# Generated by Django 4.0.4 on 2022-04-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_gos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doljnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InfoTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('middle_name', models.CharField(max_length=300)),
                ('iin', models.IntegerField(default=0, max_length=12)),
                ('birth_day', models.DateTimeField()),
                ('photo', models.ImageField(upload_to='upload')),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=60)),
                ('id_prikaz', models.CharField(max_length=60)),
                ('data_prikaz', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('doljnost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doljnost')),
            ],
        ),
    ]
