# Generated by Django 4.0.4 on 2022-04-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sinf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('iin', models.IntegerField(default=0, max_length=12)),
                ('number', models.CharField(blank=True, max_length=15)),
                ('birth_day', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('iin', models.IntegerField(default=0, max_length=12)),
                ('birth_day', models.DateTimeField()),
                ('diagnoz', models.TextField()),
                ('photo', models.ImageField(upload_to='upload')),
                ('address', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.student_parent')),
                ('pol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pol')),
                ('sinf', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.sinf')),
            ],
        ),
    ]
