# Generated by Django 4.0.4 on 2022-04-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_student_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_parent',
            name='birth_day',
            field=models.DateField(),
        ),
    ]
