# Generated by Django 4.0.4 on 2022-04-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_student_parent_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_parent',
            name='number2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='student_parent',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
