# Generated by Django 4.0.4 on 2022-04-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_student_parent_number2_alter_student_parent_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ashiqsabaq',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Calculate',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Gos',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
