# Generated by Django 4.0.4 on 2022-04-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_corpus_subject_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cabinet')),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sinf')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.infoteacher')),
            ],
        ),
    ]
