# Generated by Django 4.0.4 on 2022-04-20 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'doljnost': 'Рахбар'}, on_delete=django.db.models.deletion.CASCADE, to='main.infoteacher'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
