# Generated by Django 4.0.4 on 2022-04-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_lesson_teacher_alter_sinf_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoteacher',
            name='birth_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='infoteacher',
            name='data_prikaz',
            field=models.DateField(),
        ),
    ]
