# Generated by Django 4.0.4 on 2022-04-21 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_infoteacher_birth_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('week_day', models.CharField(max_length=300)),
                ('start_time', models.IntegerField(default=0)),
                ('stop_time', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
            ],
        ),
    ]
