# Generated by Django 4.0.4 on 2022-04-21 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_lessontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoteacher',
            name='number2',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='infoteacher',
            name='doljnost',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.doljnost'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.infoteacher'),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='stop_time',
            field=models.TimeField(),
        ),
    ]
