# Generated by Django 4.0.4 on 2022-04-22 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_lesson_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='week_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.week'),
        ),
    ]
