# Generated by Django 4.0.4 on 2022-04-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_week_alter_lessontime_week_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
    ]
