# Generated by Django 4.0.4 on 2022-05-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_student_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student_parent',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='diagnoz',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.diagnoz'),
        ),
    ]
