# Generated by Django 4.0.4 on 2022-05-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_diagnoz_student_parent_title_alter_student_diagnoz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_parent',
            name='birth_day',
        ),
    ]
