# Generated by Django 4.0.4 on 2022-04-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gos',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
